Repository KVeitch/palette-picker-front-end, pull requests merged in 2019-12, with the labels that each got.

#4 Comps
  src/components/App/App.js
  src/components/App/App.scss
  src/components/Color/Color.js
  src/components/Color/Color.scss
  src/components/InputForm/InputForm.js
  src/components/InputForm/InputForm.scss
  src/components/InputForm/InputForm.test.js
  src/components/Project/Project.js
  src/components/ProjectsContainer/ProjectsContainer.js
  src/components/ProjectsContainer/ProjectsContainer.scss
  src/components/ProjectsContainer/ProjectsContainer.test.js
Labels: MVP

#5 Api calls
  src/utils/apiCalls.js
Labels: MVP

#6 Comps
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/App/App.scss
  src/components/App/App.test.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/Color/Color.js
  src/components/Color/Color.scss
Labels: MVP, enhancement

#12 Functionality
  src/components/App/App.js
  src/components/Palette/Palette.scss
  src/components/Project/Project.js
  src/components/Project/Project.scss
  src/components/ProjectsContainer/ProjectsContainer.js
Labels: MVP

#13 Fetching
  src/components/App/App.js
  src/components/Project/Project.js
  src/components/ProjectsContainer/ProjectsContainer.js
  src/utils/apiCalls.js
  yarn.lock.old
Labels: MVP

#14 Post project
  src/components/App/App.js
  src/components/InputForm/InputForm.js
  src/utils/apiCalls.js
Labels: MVP

#15 Fixes not deleting bug
  src/components/App/App.js
Labels: bug

#16 Add styling and conditional renders
  src/components/App/App.js
  src/components/App/App.scss
  src/components/Color/Color.scss
  src/components/InputForm/InputForm.js
  src/components/InputForm/InputForm.scss
Labels: MVP

#17 Linted files
  public/index.html
  src/components/App/App.js
  src/components/App/App.scss
  src/components/App/App.test.js
  src/components/Color/Color.js
  src/components/Color/Color.scss
  src/components/Color/Color.test.js
  src/components/InputForm/InputForm.js
  src/components/InputForm/InputForm.scss
  src/components/InputForm/InputForm.test.js
  src/components/Palette/Palette.js
  src/components/Palette/Palette.scss
  src/components/Palette/Palette.test.js
  src/components/Project/Project.js
  src/components/Project/Project.scss
  src/components/Project/Project.test.js
  src/components/ProjectsContainer/ProjectsContainer.js
  src/components/ProjectsContainer/ProjectsContainer.scss
  src/components/ProjectsContainer/ProjectsContainer.test.js
  src/setupTests.js
  src/utils/apiCalls.js
  src/utils/apiCalls.test.js
Labels: MVP

#18 Improves Testing suite
  package.json
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/InputForm/InputForm.test.js
  src/components/InputForm/__snapshots__/InputForm.test.js.snap
  src/components/Project/__snapshots__/Project.test.js.snap
  src/utils/apiCalls.test.js
Labels: MVP, Testing
